version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: spotify_postgres
    environment:
      POSTGRES_DB: spotify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    env_file:
      - .env
    container_name: spotify_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/spotify
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres

  frontend:
    build: ./frontend/spotify-frontend
    container_name: spotify_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
